### ISSUE TITLE
Stream.waitForData goroutine leak

### ISSUE THREAD

**Issue by lgierth** [whyrusleeping/go-multiplex#10]
```
> curl https://ipfs.io/ipfs/QmWPNtfibbs7E78ZrNAC6GLkGF5y1U2h5T8WgbJi8KMqpD | stackparse --wait-more-than=30m --summary
[...]
gx/ipfs/QmTKsRYeY4simJyf37K93juSq75Lo8MVCDJ7owjmf46u8W/go-context/io.(*ctxReader).Read                 48
gx/ipfs/QmNhuMfExDSZvjyrUk9FkC1Cb3vqx2ErCicFwxq2f7SHbW/floodsub.(*PubSub).handleSendingMessages        53
gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux.(*Session).AcceptStream                   364
gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux.(*Stream).Read                            642
gx/ipfs/QmbX2bvPnLs2xPoJcFV7LHyn8bh3hxzwRaoEsZpmgP5hXn/go-multiplex.(*Stream).waitForData              9710
```

**Comment by lgierth** [comment]
cc @Stebalien

**Comment by Stebalien** [comment]
So, I fixed a bug that might be related here: https://github.com/whyrusleeping/go-multiplex/commit/1c4507bfd758c2bf436c9f0cb2185027f55938a1

**Comment by Stebalien** [comment]
We now believe this is a different issue. The version of go-multiplex currently used by go-ipfs will ignore Close messages from stream initiators (it didn't correctly handle message tags).

Pulling this fix into go-ipfs is blocked on merging @marten-seemann PRs.

**Comment by lgierth** [comment]
Is it possible to unblock it somehow? Is this just about a rebase of those PRs?

**Comment by Stebalien** [comment]
No, but those should be merged very soon (they're not really blocked on anything, just some basic review).

**Comment by lgierth** [comment]
Let's make sure to get this into this next release <3

**Comment by Stebalien** [comment]
That's the plan. FYI, this isn't a regression really, we just have a more js-ipfs nodes coming online (which speak go-multiplex).

**Comment by whyrusleeping** [comment]
@Stebalien this has been resolved, right?

**Comment by Stebalien** [comment]
@whyrusleeping yes.
