### ISSUE TITLE
Max message size

### ISSUE THREAD

**Issue by VictorBjelkholm** [whyrusleeping/go-multiplex#3]
Trying to test out the interop between js-libp2p and go-libp2p. Get stuck when I send things bigger than 1024 bytes, and they become cropped at that size.

I'm using the echo examples from both go-libp2p and js-libp2p-ipfs-nodejs to test the interop.

Progress is in this PR: https://github.com/ipfs/js-libp2p-ipfs-nodejs/pull/55

Screenshot from it in action:
<img width="1280" alt="go-libp2p_js-libp2p-interop" src="https://cloud.githubusercontent.com/assets/459764/22246101/7405ebec-e233-11e6-8bde-bbc2d059762c.png">

**Comment by whyrusleeping** [comment]
Probably because the echo example only reads 1024 bytes: https://github.com/libp2p/go-libp2p/blob/master/examples/echo/main.go#L147

**Comment by VictorBjelkholm** [comment]
Yeah, I discovered that as well. So I tried changing that to 1024 * 1024,
and it'll just report that it cannot write to a closed stream. Seems to be
another limit somewhere.

**Comment by whyrusleeping** [comment]
It also only reads/writes once. The program was not intended to do what you think it was. I can change it to work better for your purpose though
